name: Release

on:
  workflow_dispatch:
    inputs:
        app:
          type: choice
          options: 
            - my-app1
            - my-app2

permissions: write-all

jobs:
  make-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - run: |
          git config --global user.email "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"
          git config --global user.name "${{ github.triggering_actor }}"

      - run: npm ci --legacy-peer-deps
      - run: npx nx release --projects=${{ inputs.app }} --skip-publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-deploy-statging-app:
    runs-on: ubuntu-latest
    needs: make-release
    environment: Staging
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Cache node_modules
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - run: npm ci --legacy-peer-deps
      - run: npx nx build ${{ inputs.app }}
      - run: echo Deploy

  build-deploy-prod-app:
    runs-on: ubuntu-latest
    needs: build-deploy-statging-app
    environment: Prod
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Cache node_modules
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - run: npm ci --legacy-peer-deps
      - run: npx nx build ${{ inputs.app }}
      - run: echo Deploy